#define ADD(x,y) NodeCtor (OP, F_ADD, x,    y)
#define SUB(x,y) NodeCtor (OP, F_SUB, x,    y)
#define MUL(x,y) NodeCtor (OP, F_MUL, x,    y)
#define DIV(x,y) NodeCtor (OP, F_DIV, x,    y)
#define COS(x)   NodeCtor (OP, F_COS, NULL, x)
#define SIN(x)   NodeCtor (OP, F_SIN, NULL, x)
#define ST(x, y) NodeCtor (OP, F_DEG, x,    y)
#define LN(x)    NodeCtor (OP, F_LN,  NULL, x)
#define CONST(c) NodeCtor (NUM, c, NULL, NULL)

#define EXP(x) NodeCtor (OP, '^', NodeCtor (MATH_CONST, 'e', NULL, NULL), x)

#define dl Diff     (node->left, file)
#define dr Diff     (node->right, file)
#define cl CopyNode (node->left)
#define cr CopyNode (node->right)
